name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: master

env:
  CI: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 1
    - uses: actions/setup-node@v6
    - run: npm install
    - run: npm run lint
